### PR TITLE
11052 upgraded follow redirects with npm audit fix, bumped version

### PR DESCRIPTION
**Pull request by michaeljwiebe**

### CODE REVIEW

**Comment by michaeljwiebe** [comment]
there are tests for this repo but i was unable to run them due to not having an .env file

**Comment by michaeljwiebe** [comment]
27 tests passed, 40 failed with 401s

**Comment by michaeljwiebe** [comment]
The following tests run from our github similar-web-js package failed with 401 status codes.

 FAIL  src/components/salesSolution/SalesSolution.test.ts
  ● service.salesSolution › lead enrichment › should get
      path: v1/website/${domain}/lead-enrichment/all

 FAIL  src/components/mobileWebTrafficSources/MobileWebTrafficSources.test.ts
  ● service.desktopWebTrafficSources › overview share › should get
      path: v1/website/${domain}/traffic-sources/mobile-overview-share
  ● service.desktopWebTrafficSources › referrals › should get
      path: v1/website/${domain}/traffic-sources/mobileweb-referrals

 FAIL  src/components/utilities/Utilities.test.ts
  ● service.utilities › capabilities › should get
      path: capabilities

 FAIL  src/components/desktopKeywordAnalysis/DesktopKeywordAnalysis.test.ts
  ● service.desktopKeywordAnalysis › competitors organic › should get
      path: v1/website/${domain}/search-competitors/organicsearchcompetitors
  ● service.desktopKeywordAnalysis › competitors paid › should get
      path: v1/website/${domain}/search-competitors/paidsearchcompetitors
  ● service.desktopKeywordAnalysis › analyze organic › should get
      path: v1/keywords/${keyword}/analysis/organic-competitors
  ● service.desktopKeywordAnalysis › analyze paid › should get
      path: v1/keywords/${keyword}/analysis/paid-competitors

 FAIL  src/components/totalTraffic/TotalTraffic.test.ts
  ● service.totalTraffic › visits › should get
      path: v1/website/${domain}/total-traffic-and-engagement/visits
  ● service.totalTraffic › pages / visits › should get
      path: v1/website/${domain}/total-traffic-and-engagement/pages-per-visit
  ● service.totalTraffic › average visit duration › should get
      path: v1/website/${domain}/total-traffic-and-engagement/average-visit-duration
  ● service.totalTraffic › bounce rate › should get
      path: v1/website/${domain}/total-traffic-and-engagement/bounce-rate
  ● service.totalTraffic › desktop mobile split › should get
      path: v1/website/${domain}/total-traffic-and-engagement/visits-split
  ● service.totalTraffic › deduplicated audience › should get
      path: v1/website/${domain}/dedup/deduplicated-audiences

 FAIL  src/components/desktopOther/DesktopOther.test.ts
  ● service.desktopOther › similar sites › should get
      path: v1/website/${domain}/similar-sites/similarsites
  ● service.desktopOther › audience interest › should get
      path: v1/website/${domain}/audience-interests/also-visited
  ● service.desktopOther › category rank › should get
      path: v1/website/${domain}/category-rank/category-rank
  ● service.desktopOther › top sites desktop › should get
      path: v1/website/${category}/topsites/describe
  ● service.desktopOther › top sites mobile › should get
      path: v1/website/${category}/topsitesmobile/describe
  ● service.desktopOther › api lite › should get
      path: v1/website/${domain}/general-data/all

 FAIL  src/components/desktopWebTrafficSources/DesktopWebTrafficSources.test.ts (5.587 s)
  ● service.desktopWebTrafficSources › overview › should get
      path: v1/website/${domain}/traffic-sources/overview
  ● service.desktopWebTrafficSources › overview share › should get
      path: v1/website/${domain}/traffic-sources/overview-share
  ● service.desktopWebTrafficSources › pages per visit › should get
      path: v1/website/${domain}/traffic-sources/engagement-metrics/pages-per-visit
  ● service.desktopWebTrafficSources › average visit duration › should get
      path: v1/website/${domain}/traffic-sources/engagement-metrics/average-duration
  ● service.desktopWebTrafficSources › bounce rate › should get
      path: v1/website/${domain}/traffic-sources/engagement-metrics/bounce-rate
  ● service.desktopWebTrafficSources › social referrals › should get
      path: v1/website/${domain}/traffic-sources/social
  ● service.desktopWebTrafficSources › referrals › should get
      path: v1/website/${domain}/traffic-sources/referrals
  ● service.desktopWebTrafficSources › ad networks › should get
      path: v1/website/${domain}/traffic-sources/ad-networks
  ● service.desktopWebTrafficSources › publishers › should get
      path: v1/website/${domain}/traffic-sources/publishers
  ● service.desktopWebTrafficSources › search keywords › should get organic
      path: v1/website/${domain}/traffic-sources/organic-search
  ● service.desktopWebTrafficSources › search keywords › should get paid
      path: v1/website/${domain}/traffic-sources/paid-search
  ● service.desktopWebTrafficSources › search keywords › should get branded
      path: v1/website/${domain}/traffic-sources/branded-search
  ● service.desktopWebTrafficSources › search keywords › should get non-branded
      path: v1/website/${domain}/traffic-sources/nonbranded-search
  ● service.desktopWebTrafficSources › search keywords › should get questions
      path: v1/website/${domain}/traffic-sources/questions-search
  ● service.desktopWebTrafficSources › search visits distribution › should get
      path: v1/website/${domain}/traffic-sources/search-visits-distribution
  ● service.desktopWebTrafficSources › organic outgoing links › should get
      path: v1/website/${domain}/traffic-sources/outgoing-referrals
  ● service.desktopWebTrafficSources › outgoing ad networks › should get
      path: v1/website/${domain}/traffic-sources/outgoing-referrals
  ● service.desktopWebTrafficSources › outgoing ad advertisers › should get
      path: v1/website/${domain}/traffic-sources/outgoing-ads-advertisers

**Comment by lancegliser** [comment]
Thanks for opening #18. We'll allow the security upgrade for that to move forward. Will have to circle back to those other tests.

**Pull request merged**
